//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
// 
#pragma warning disable 1591

namespace WebService.refService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceRasControlSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceRasControl : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback XmlBurnDownOperationCompleted;
        
        private System.Threading.SendOrPostCallback XmlDesempenhoMembrosProjetoOperationCompleted;
        
        private System.Threading.SendOrPostCallback XmlBurnUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarPermissaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarPermissaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletarPermissaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarPermissaoPorIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarAllPermissaoFiltrosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarPermissoesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceRasControl() {
            this.Url = global::WebService.Properties.Settings.Default.WebService_localhost_WebServiceRasControl;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event XmlBurnDownCompletedEventHandler XmlBurnDownCompleted;
        
        /// <remarks/>
        public event XmlDesempenhoMembrosProjetoCompletedEventHandler XmlDesempenhoMembrosProjetoCompleted;
        
        /// <remarks/>
        public event XmlBurnUpCompletedEventHandler XmlBurnUpCompleted;
        
        /// <remarks/>
        public event CadastrarPermissaoCompletedEventHandler CadastrarPermissaoCompleted;
        
        /// <remarks/>
        public event AlterarPermissaoCompletedEventHandler AlterarPermissaoCompleted;
        
        /// <remarks/>
        public event DeletarPermissaoCompletedEventHandler DeletarPermissaoCompleted;
        
        /// <remarks/>
        public event ConsultarPermissaoPorIdCompletedEventHandler ConsultarPermissaoPorIdCompleted;
        
        /// <remarks/>
        public event ConsultarAllPermissaoFiltrosCompletedEventHandler ConsultarAllPermissaoFiltrosCompleted;
        
        /// <remarks/>
        public event ListarPermissoesCompletedEventHandler ListarPermissoesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XmlBurnDown", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode XmlBurnDown(int idProjeto, int idSprint) {
            object[] results = this.Invoke("XmlBurnDown", new object[] {
                        idProjeto,
                        idSprint});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void XmlBurnDownAsync(int idProjeto, int idSprint) {
            this.XmlBurnDownAsync(idProjeto, idSprint, null);
        }
        
        /// <remarks/>
        public void XmlBurnDownAsync(int idProjeto, int idSprint, object userState) {
            if ((this.XmlBurnDownOperationCompleted == null)) {
                this.XmlBurnDownOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXmlBurnDownOperationCompleted);
            }
            this.InvokeAsync("XmlBurnDown", new object[] {
                        idProjeto,
                        idSprint}, this.XmlBurnDownOperationCompleted, userState);
        }
        
        private void OnXmlBurnDownOperationCompleted(object arg) {
            if ((this.XmlBurnDownCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XmlBurnDownCompleted(this, new XmlBurnDownCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XmlDesempenhoMembrosProjeto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode XmlDesempenhoMembrosProjeto(int idProjeto) {
            object[] results = this.Invoke("XmlDesempenhoMembrosProjeto", new object[] {
                        idProjeto});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void XmlDesempenhoMembrosProjetoAsync(int idProjeto) {
            this.XmlDesempenhoMembrosProjetoAsync(idProjeto, null);
        }
        
        /// <remarks/>
        public void XmlDesempenhoMembrosProjetoAsync(int idProjeto, object userState) {
            if ((this.XmlDesempenhoMembrosProjetoOperationCompleted == null)) {
                this.XmlDesempenhoMembrosProjetoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXmlDesempenhoMembrosProjetoOperationCompleted);
            }
            this.InvokeAsync("XmlDesempenhoMembrosProjeto", new object[] {
                        idProjeto}, this.XmlDesempenhoMembrosProjetoOperationCompleted, userState);
        }
        
        private void OnXmlDesempenhoMembrosProjetoOperationCompleted(object arg) {
            if ((this.XmlDesempenhoMembrosProjetoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XmlDesempenhoMembrosProjetoCompleted(this, new XmlDesempenhoMembrosProjetoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XmlBurnUp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode XmlBurnUp(int idProjeto, int idSprint) {
            object[] results = this.Invoke("XmlBurnUp", new object[] {
                        idProjeto,
                        idSprint});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void XmlBurnUpAsync(int idProjeto, int idSprint) {
            this.XmlBurnUpAsync(idProjeto, idSprint, null);
        }
        
        /// <remarks/>
        public void XmlBurnUpAsync(int idProjeto, int idSprint, object userState) {
            if ((this.XmlBurnUpOperationCompleted == null)) {
                this.XmlBurnUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXmlBurnUpOperationCompleted);
            }
            this.InvokeAsync("XmlBurnUp", new object[] {
                        idProjeto,
                        idSprint}, this.XmlBurnUpOperationCompleted, userState);
        }
        
        private void OnXmlBurnUpOperationCompleted(object arg) {
            if ((this.XmlBurnUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XmlBurnUpCompleted(this, new XmlBurnUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastrarPermissao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarPermissao(Permissao permissao) {
            this.Invoke("CadastrarPermissao", new object[] {
                        permissao});
        }
        
        /// <remarks/>
        public void CadastrarPermissaoAsync(Permissao permissao) {
            this.CadastrarPermissaoAsync(permissao, null);
        }
        
        /// <remarks/>
        public void CadastrarPermissaoAsync(Permissao permissao, object userState) {
            if ((this.CadastrarPermissaoOperationCompleted == null)) {
                this.CadastrarPermissaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarPermissaoOperationCompleted);
            }
            this.InvokeAsync("CadastrarPermissao", new object[] {
                        permissao}, this.CadastrarPermissaoOperationCompleted, userState);
        }
        
        private void OnCadastrarPermissaoOperationCompleted(object arg) {
            if ((this.CadastrarPermissaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarPermissaoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlterarPermissao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AlterarPermissao(Permissao permissao) {
            this.Invoke("AlterarPermissao", new object[] {
                        permissao});
        }
        
        /// <remarks/>
        public void AlterarPermissaoAsync(Permissao permissao) {
            this.AlterarPermissaoAsync(permissao, null);
        }
        
        /// <remarks/>
        public void AlterarPermissaoAsync(Permissao permissao, object userState) {
            if ((this.AlterarPermissaoOperationCompleted == null)) {
                this.AlterarPermissaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarPermissaoOperationCompleted);
            }
            this.InvokeAsync("AlterarPermissao", new object[] {
                        permissao}, this.AlterarPermissaoOperationCompleted, userState);
        }
        
        private void OnAlterarPermissaoOperationCompleted(object arg) {
            if ((this.AlterarPermissaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarPermissaoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeletarPermissao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeletarPermissao(int idPermissao) {
            this.Invoke("DeletarPermissao", new object[] {
                        idPermissao});
        }
        
        /// <remarks/>
        public void DeletarPermissaoAsync(int idPermissao) {
            this.DeletarPermissaoAsync(idPermissao, null);
        }
        
        /// <remarks/>
        public void DeletarPermissaoAsync(int idPermissao, object userState) {
            if ((this.DeletarPermissaoOperationCompleted == null)) {
                this.DeletarPermissaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletarPermissaoOperationCompleted);
            }
            this.InvokeAsync("DeletarPermissao", new object[] {
                        idPermissao}, this.DeletarPermissaoOperationCompleted, userState);
        }
        
        private void OnDeletarPermissaoOperationCompleted(object arg) {
            if ((this.DeletarPermissaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletarPermissaoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarPermissaoPorId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Permissao ConsultarPermissaoPorId(int idPermissao) {
            object[] results = this.Invoke("ConsultarPermissaoPorId", new object[] {
                        idPermissao});
            return ((Permissao)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPermissaoPorIdAsync(int idPermissao) {
            this.ConsultarPermissaoPorIdAsync(idPermissao, null);
        }
        
        /// <remarks/>
        public void ConsultarPermissaoPorIdAsync(int idPermissao, object userState) {
            if ((this.ConsultarPermissaoPorIdOperationCompleted == null)) {
                this.ConsultarPermissaoPorIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPermissaoPorIdOperationCompleted);
            }
            this.InvokeAsync("ConsultarPermissaoPorId", new object[] {
                        idPermissao}, this.ConsultarPermissaoPorIdOperationCompleted, userState);
        }
        
        private void OnConsultarPermissaoPorIdOperationCompleted(object arg) {
            if ((this.ConsultarPermissaoPorIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPermissaoPorIdCompleted(this, new ConsultarPermissaoPorIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarAllPermissaoFiltros", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Permissao[] ConsultarAllPermissaoFiltros(int codigo, string descricao) {
            object[] results = this.Invoke("ConsultarAllPermissaoFiltros", new object[] {
                        codigo,
                        descricao});
            return ((Permissao[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarAllPermissaoFiltrosAsync(int codigo, string descricao) {
            this.ConsultarAllPermissaoFiltrosAsync(codigo, descricao, null);
        }
        
        /// <remarks/>
        public void ConsultarAllPermissaoFiltrosAsync(int codigo, string descricao, object userState) {
            if ((this.ConsultarAllPermissaoFiltrosOperationCompleted == null)) {
                this.ConsultarAllPermissaoFiltrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarAllPermissaoFiltrosOperationCompleted);
            }
            this.InvokeAsync("ConsultarAllPermissaoFiltros", new object[] {
                        codigo,
                        descricao}, this.ConsultarAllPermissaoFiltrosOperationCompleted, userState);
        }
        
        private void OnConsultarAllPermissaoFiltrosOperationCompleted(object arg) {
            if ((this.ConsultarAllPermissaoFiltrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarAllPermissaoFiltrosCompleted(this, new ConsultarAllPermissaoFiltrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarPermissoes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Permissao[] ListarPermissoes() {
            object[] results = this.Invoke("ListarPermissoes", new object[0]);
            return ((Permissao[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarPermissoesAsync() {
            this.ListarPermissoesAsync(null);
        }
        
        /// <remarks/>
        public void ListarPermissoesAsync(object userState) {
            if ((this.ListarPermissoesOperationCompleted == null)) {
                this.ListarPermissoesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarPermissoesOperationCompleted);
            }
            this.InvokeAsync("ListarPermissoes", new object[0], this.ListarPermissoesOperationCompleted, userState);
        }
        
        private void OnListarPermissoesOperationCompleted(object arg) {
            if ((this.ListarPermissoesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarPermissoesCompleted(this, new ListarPermissoesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Permissao {
        
        private int codigoField;
        
        private string descricaoField;
        
        private string observacaoField;
        
        private string erroField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string Observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Erro {
            get {
                return this.erroField;
            }
            set {
                this.erroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void XmlBurnDownCompletedEventHandler(object sender, XmlBurnDownCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XmlBurnDownCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XmlBurnDownCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void XmlDesempenhoMembrosProjetoCompletedEventHandler(object sender, XmlDesempenhoMembrosProjetoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XmlDesempenhoMembrosProjetoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XmlDesempenhoMembrosProjetoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void XmlBurnUpCompletedEventHandler(object sender, XmlBurnUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XmlBurnUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XmlBurnUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CadastrarPermissaoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AlterarPermissaoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeletarPermissaoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultarPermissaoPorIdCompletedEventHandler(object sender, ConsultarPermissaoPorIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPermissaoPorIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPermissaoPorIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Permissao Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Permissao)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConsultarAllPermissaoFiltrosCompletedEventHandler(object sender, ConsultarAllPermissaoFiltrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarAllPermissaoFiltrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarAllPermissaoFiltrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Permissao[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Permissao[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListarPermissoesCompletedEventHandler(object sender, ListarPermissoesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarPermissoesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarPermissoesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Permissao[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Permissao[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591